version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/blitz-first:delegated
      - node_modules:/blitz-first/node_modules
    ports:
      - 3080:3000
      # - 9229:9229
    # env_file:
    #   - ../.env
    working_dir: /blitz-first
    tty: true
volumes:
  node_modules:
